inputs: assets/demo/layout_detection
outputs: outputs/layout_detection
tasks:
  layout_detection:
    model: layout_detection_yolo
    model_config:
      img_size: 1024    # 1024 for doclayout_yolo_ft.pt, 1280 for doclayout_yolo_docstructbench_imgsz1280_2501.pt
      conf_thres: 0.25
      iou_thres: 0.45
      model_path: models/Layout/YOLO/doclayout_yolo_ft.pt
      visualize: True